const products = [
  {
    id: "p1",
    model: "MT8051iP",
    screenSize: 4.3,
    width: 480,
    height: 272,
    flashMemory: 128,
    ramMemory: 128,
    flashMemUnit: "MB",
    ramMemUnit: "MB",
    maxTemp: 50,
  },
  {
    id: "p2",
    model: "MT8951iP",
    screenSize: 8.2,
    width: 400,
    height: 700,
    flashMemory: 500,
    ramMemory: 500,
    flashMemUnit: "MB",
    ramMemUnit: "MB",
    maxTemp: 70,
  },
  {
    id: "p3",
    model: "MT8041iP",
    screenSize: 7.1,
    width: 800,
    height: 1000,
    flashMemory: 2,
    ramMemory: 2,
    flashMemUnit: "GB",
    ramMemUnit: "GB",
    maxTemp: 60,
  },
  {
    id: "p4",
    model: "MT8102iP",
    screenSize: 7.3,
    width: 880,
    height: 1080,
    flashMemory: 128,
    ramMemory: 8,
    flashMemUnit: "GB",
    ramMemUnit: "GB",
    maxTemp: 60,
  },
  {
    id: "p5",
    model: "MT8251iP",
    screenSize: 8.3,
    width: 780,
    height: 1072,
    flashMemory: 700,
    ramMemory: 700,
    flashMemUnit: "MB",
    ramMemUnit: "MB",
    maxTemp: 50,
  },
];

export default products;
